### ISSUE TITLE
Mention VM in the 02-cpp-hello-world and in setup

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2021-lesson-preexercise-cpp-and-root#1]
For the sake of consistency, the VM should be mentioned in the first sentence of https://cms-opendata-workshop.github.io/workshop2021-lesson-preexercise-cpp-and-root/02-cpp-hello-world/index.html
and in https://cms-opendata-workshop.github.io/workshop2021-lesson-preexercise-cpp-and-root/setup.html

Add a mention that, alternatively, this exercise can also be done in the CMS shell of the VM image in case that option was chosen https://cms-opendata-workshop.github.io/workshop2021-lesson-virtualmachine/

This could be done in a similar way as in the CMSSW lesson in https://cms-opendata-workshop.github.io/workshop2021-lesson-cmssw/

**Comment by mattbellis** [comment]
Done! Rewrote the setup to mention VMs. 

Copied over introductory text and image from the CMSSW pre-exercise for consistencies sake.
